from enum import Enum

WIDTH = 2240
HEIGHT = 1400
INTERVAL = 40
LAYER_OFFSET = 140
GRADIENT_OFFSET = 160
INTERIOR_OFFSET = 180
LAYER_WIDTH = WIDTH - LAYER_OFFSET * 2
LAYER_HEIGHT = HEIGHT - LAYER_OFFSET * 2
GRADIENT_WIDTH = WIDTH - GRADIENT_OFFSET * 2
GRADIENT_HEIGHT = HEIGHT - GRADIENT_OFFSET * 2

INTERIOR_ORIGIN = (INTERIOR_OFFSET, INTERIOR_OFFSET)
ORIGIN = (0, 0)


class QuadrantEnum(Enum):
    FIRST = 1
    SECOND = 2
    THIRD = 3
    FOURTH = 4


class SlopeEnum(Enum):
    DEFAULT = 1
    HORIZONTAL = 2
    VERTICAL = 3


class IntervalEnum(Enum):
    HORIZONTAL = 1
    VERTICAL = 2


class Corners:
    TOP_LEFT = (0, 0)
    TOP_RIGHT = (WIDTH, 0)
    BOTTOM_RIGHT = (WIDTH, HEIGHT)
    BOTTOM_LEFT = (0, HEIGHT)


class Colors:
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    CYAN = (0, 255, 255)
    MAGENTA = (255, 0, 255)
    YELLOW = (255, 255, 0)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLUE = (0, 0, 255)
